logging:
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  datefmt: '%Y-%m-%d %H:%M:%S'
  log_file: 'graph.log'

ollama:
  model: llama3.2:1b
  temperature: 0

azureopenai:
  temperature: 0

launch:
  model: azureai
  embeddings: azureai
  turbo_model: None
