from pathlib import Path

CORE_PACKAGE_PATH = Path(__file__).resolve().parent.parent
SRC_DIRECTORY_PATH = CORE_PACKAGE_PATH.parent
PROJECT_ROOT_PATH = SRC_DIRECTORY_PATH.parent
LOGS_DIRECTORY_PATH = PROJECT_ROOT_PATH / "logs"
ARTIFACTS_DIRECTORY_PATH = PROJECT_ROOT_PATH / "artifacts"
CONFIG_DIRECTORY_PATH = CORE_PACKAGE_PATH / "config"
CONFIG_FILE_PATH = CONFIG_DIRECTORY_PATH / "config.yml"
CONFIG_NODES_FILE_PATH = CONFIG_DIRECTORY_PATH / "config_nodes.yml"

